### ISSUE TITLE
Question about baselines

### ISSUE THREAD

**Issue by ivan-chai** [iLampard/hypro_tpp#2]
Dear authors of the HYPRO,

Thank you for publishing the paper and sharing the official implementation of the method!

I try to understand the experimental setup and come to the following questions:
1. How can I reproduce the results for baseline methods (NHP, DualTPP, etc.)?
2. Did you use sampling, expectation, or maximum likelihood prediction for the baselines?
3. Did you compare the proposed rescoring method with a beam search?

Looking forward to your reply and would be very grateful for any clarifications.

**Comment by iLampard** [comment]
Hi Ivan

> 1. How can I reproduce the results for baseline methods (NHP, DualTPP, etc.)?

For NHP, please use either EasyTPP or the code in [AttNHP](https://github.com/yangalan123/anhp-andtt/tree/master/anhp/model) ( you need to deactivate the att block).

For DualTPP, we use the author's code.


> 2. Did you use sampling, expectation, or maximum likelihood prediction for the baselines?

We use what the original code provides. For NHP it is maximum likelihood prediction. For DualTPP, i forgot, maybe not maximum likelihood prediction. 


> 3. Did you compare the proposed rescoring method with a beam search?

No. 


> 
> Looking forward to your reply and would be very grateful for any clarifications.
